pipeline {
    agent any

    tools {
        maven 'Maven 3'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                dir('loco/loco') {
                    // Build and run tests
                    sh 'mvn clean package -DskipTests=false'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('loco/loco') {
                    withSonarQubeEnv('SonarQube') {
                        sh 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=loco-analyzer'
                    }
                }
            }
        }

        stage("Quality Gate") {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Package App') {
            steps {
                dir('loco/loco') {
                    sh '''
                    # Clean previous output
                    rm -rf output

                    # IMPORTANT: Copy main jar to target/libs for jpackage
                    # generated by maven-dependency-plugin usually only copies dependencies
                    mkdir -p target/libs
                    cp target/loco-1.0-SNAPSHOT.jar target/libs/

                    # Run JPackage for Linux
                    jpackage --name Loco \
                             --input target/libs \
                             --main-jar loco-1.0-SNAPSHOT.jar \
                             --main-class com.myapp.loco.MainApp \
                             --type app-image \
                             --dest output \
                             --java-options "--module-path \\$APPDIR/lib/app --add-modules javafx.controls,javafx.fxml"

                    # Fix duplicate JavaFX jars for Linux runtime
                    cp target/libs/javafx-*-linux.jar output/Loco/lib/app/
                    rm -f output/Loco/lib/app/javafx-base-17.0.2.jar
                    rm -f output/Loco/lib/app/javafx-controls-17.0.2.jar
                    rm -f output/Loco/lib/app/javafx-fxml-17.0.2.jar
                    rm -f output/Loco/lib/app/javafx-graphics-17.0.2.jar

                    # Compress
                    tar -czf loco-admin-linux.tar.gz -C output Loco
                    '''
                }
            }
        }
    }

    post {
        success {
            dir('loco/loco') {
                archiveArtifacts artifacts: 'loco-admin-linux.tar.gz', fingerprint: true
            }
        }
    }
}
